name: "install-kind"
description: "Installs kind CLI"
inputs:
  version:
    description: kind version to install
    default: latest
    required: true
runs:
  using: "composite"
  steps:
  - name: Install kind
    uses: reconcilerio/go-install-action@v1
    with:
      package: sigs.k8s.io/kind
      version: "${{ inputs.version }}"
      download-url-template: https://github.com/kubernetes-sigs/kind/releases/download/${version}/kind-${os}-${arch}
      output-dir: /usr/local/bin
