name: "install-cloud-provider-kind"
description: "Installs cloud-provider-kind CLI"
inputs:
  version:
    description: cloud-provider-kind version to install
    default: latest
    required: true
runs:
  using: "composite"
  steps:
  - name: Build cloud-provider-kind, if unable to download
    if: steps.download-cloud-provider-kind.outcome == 'failure'
    uses: reconcilerio/go-install-action@v1
    with:
      package: sigs.k8s.io/cloud-provider-kind
      version: "${{ inputs.version }}"
      download-url-template: https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/${version}/cloud-provider-kind_${version:1}_${os}_${arch}.tar.gz
      download-path-within-archive: cloud-provider-kind
      output-dir: /usr/local/bin
