name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
    tags:
    # semver tags
    - 'v[0-9]+\.[0-9]+\.[0-9]+-?**'
  pull_request: {}

jobs:

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-24.04
        - os: ubuntu-24.04-arm
        - os: macos-26
        - os: macos-26-intel
        - with:
            version: latest
          with-cloud-provider-kind:
            version: latest
        - with:
            version: v0.30.0
          with-cloud-provider-kind:
            version: v0.9.0
        - with:
            version: main
          with-cloud-provider-kind:
            version: main
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-go@v6
      with:
        go-version: stable
    - uses: ./
      with: ${{ matrix.with || fromJson('{}') }}
    - name: kind version
      run: |
        set -euo pipefail

        echo "installed to: $( which kind )"
        echo "kind version: $( kind --version )"
    - uses: ./cloud-provider-kind/
      with: ${{ matrix.with-cloud-provider-kind || fromJson('{}') }}
    - name: cloud-provider-kind test
      run: |
        set -euo pipefail

        echo "installed to: $( which cloud-provider-kind )"
        cloud-provider-kind --help
